### ISSUE TITLE
Switch doesn't detect Blood

### ISSUE THREAD

**Issue by Dzierzan** [Jan200101/NXBlood#1]
Hey. So I tried to follow the steps and my Switch doesn't detect Blood game. As I understand, I should put NRO file inside newly created folder named "switch" and create another folder named "nblood" and there put all necessary Blood files including pk3 file from your repo. This however doesn't work. Any ideas why?

**Comment by Jan200101** [comment]
just to be sure
NXBlood is a homebrew port and requires access to the homebrew menu.
It won't show up as a normal game

if you do have homebrew the nro should be accessable from the homebrew menu and it should load the game files under /nblood on the SD cards root

**Comment by Dzierzan** [comment]
Ahh I see, it wasn't stated anywhere where it should. Then I'll pass then. Thanks!

**Comment by Jan200101** [comment]
I'll add a mention in the README
